.TH "main.Calculator" 3 "Mon Apr 12 2021" "Version 0.1" "IVS-Projekt_2-Calc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.Calculator
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self)"
.br
.ti -1c
.RI "def \fBgetMemory\fP (self)"
.br
.ti -1c
.RI "def \fBsetMemory\fP (self)"
.br
.ti -1c
.RI "def \fBgetOperand\fP (self)"
.br
.ti -1c
.RI "def \fBsetOperand\fP (self)"
.br
.ti -1c
.RI "def \fBexecuteOperation\fP (self)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBID_Operation\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalue1\fP = 0"
.br
.ti -1c
.RI "int \fBvalue2\fP = 0"
.br
.ti -1c
.RI "string \fBID_Operation\fP = ''"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Stores values of memory and contains operands methods

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def main\&.Calculator\&.__init__ ( self)"

.PP
.nf
Constructor
Every parameter will be set to zero

.fi
.PP
 
.SH "Member Function Documentation"
.PP 
.SS "def main\&.Calculator\&.executeOperation ( self)"

.PP
.nf
@brief Executes operation depending on ID of operation
@param ID_Operation:
@return Result of operation

.fi
.PP
 
.SS "def main\&.Calculator\&.getMemory ( self)"

.PP
.nf
Return values currently stored on memory
@return Last saved answr

.fi
.PP
 
.SS "def main\&.Calculator\&.getOperand ( self)"

.PP
.nf
Read from In.

.fi
.PP
 
.SS "def main\&.Calculator\&.setMemory ( self)"

.PP
.nf
Set memory on current value

.fi
.PP
 
.SS "def main\&.Calculator\&.setOperand ( self)"

.PP
.nf
Set ID of next operation depending on opration entered

.fi
.PP
 

.SH "Author"
.PP 
Generated automatically by Doxygen for IVS-Projekt_2-Calc from the source code\&.
