.TH "math_lib" 3 "Mon Apr 12 2021" "Version 0.1" "IVS-Projekt_2-Calc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
math_lib \- Implementation of basic matematic function\&.  

.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBabsolute_value\fP (number)"
.br
.ti -1c
.RI "def \fBfactorial\fP (number)"
.br
.ti -1c
.RI "def \fBnth_root\fP (root, base)"
.br
.ti -1c
.RI "def \fBsummary\fP (summmand1, summand2)"
.br
.ti -1c
.RI "def \fBsubtraction\fP (minuend, subtrahend)"
.br
.ti -1c
.RI "def \fBdivision\fP (dividend, divisor)"
.br
.ti -1c
.RI "def \fBmultiplication\fP (multiplicand, multiplier)"
.br
.ti -1c
.RI "def \fBnth_power\fP (base, exponent)"
.br
.ti -1c
.RI "def \fBshow_error\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Implementation of basic matematic function\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for IVS-Projekt_2-Calc from the source code\&.
