.TH "md__home_vladimir_fit_IVS_Projekt2_IVS_Projekt_2_Intr_net_README" 3 "Mon Apr 12 2021" "Version 0.1" "IVS-Projekt_2-Calc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_vladimir_fit_IVS_Projekt2_IVS_Projekt_2_Intr_net_README \- IVS-Projekt-2_Intr-net 
IVS Projekt-2
.SH "Vývojové prostredie:"
.PP
Ubuntu 64-bit MacOS 64-bit
.SH "Tým:"
.PP
Intr_net
.SH "Autori:"
.PP
Vladimír Mečiar xmecia00 Filip Tichý xtichy31 Matěj Šauer xsauer03 Václav Polaštík xpolas41
.SH "Licencia:"
.PP
Program je poskytovaný s licenciou GNU General Public ver\&. 3 
