.TH "memory_operation" 3 "Mon Apr 12 2021" "Version 0.1" "IVS-Projekt_2-Calc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
memory_operation
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "def \fBmemory_recall\fP ()"
.br
.ti -1c
.RI "def \fBdisplay_clear\fP ()"
.br
.ti -1c
.RI "def \fBmemory_clear\fP ()"
.br
.ti -1c
.RI "def \fBhint_show_man\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
@package

    Contains operations with memory

.fi
.PP
 
.SH "Function Documentation"
.PP 
.SS "def memory_operation\&.display_clear ()"

.PP
.nf
 Clears the display but will not delete last saved answer 
.fi
.PP
 
.SS "def memory_operation\&.hint_show_man ()"

.PP
.nf
 Will open man.pdf 
.fi
.PP
 
.SS "def memory_operation\&.memory_clear ()"

.PP
.nf
 Clears display and deletes last saved answer
.fi
.PP
 
.SS "def memory_operation\&.memory_recall ()"

.PP
.nf
 Print ANS 
.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for IVS-Projekt_2-Calc from the source code\&.
