import tkinter as tk

calc = tk.Tk()
calc.title("Calculator")
calc.minsize(300, 200)

tk.Grid.rowconfigure(calc, 0, weight=1)
for i in range(5):
    tk.Grid.columnconfigure(calc, i, weight=1)

display = tk.Entry(calc, width=30)
display.grid(row=0, column=0, columnspan=5, sticky="nesw")
display.config(justify="right")

num_0 = tk.Button(calc, text="0")
num_0.grid(row=5, column=0, sticky="nesw")
num_1 = tk.Button(calc, text="1")
num_1.grid(row=4, column=0, sticky="nesw")
num_2 = tk.Button(calc, text="2")
num_2.grid(row=4, column=1, sticky="nesw")
num_3 = tk.Button(calc, text="3")
num_3.grid(row=4, column=2, sticky="nesw")
num_4 = tk.Button(calc, text="4")
num_4.grid(row=3, column=0, sticky="nesw")
num_5 = tk.Button(calc, text="5")
num_5.grid(row=3, column=1, sticky="nesw")
num_6 = tk.Button(calc, text="6")
num_6.grid(row=3, column=2, sticky="nesw")
num_7 = tk.Button(calc, text="7")
num_7.grid(row=2, column=0, sticky="nesw")
num_8 = tk.Button(calc, text="8")
num_8.grid(row=2, column=1, sticky="nesw")
num_9 = tk.Button(calc, text="9")
num_9.grid(row=2, column=2, sticky="nesw")
n_root = tk.Button(calc, text="x^1/n")
n_root.grid(row=1, column=3, sticky="nesw")
n_power = tk.Button(calc, text="x^n")
n_power.grid(row=1, column=2, sticky="nesw")
absolute_value = tk.Button(calc, text="|x|")
absolute_value.grid(row=4, column=4, sticky="nesw")
factorial = tk.Button(calc, text="x!")
factorial.grid(row=3, column=4, sticky="nesw")
all_clear = tk.Button(calc, text="AC")
all_clear.grid(row=1, column=4, sticky="nesw")
clear = tk.Button(calc, text="C")
clear.grid(row=2, column=4, sticky="nesw")
l_bracket = tk.Button(calc, text="(")
l_bracket.grid(row=1, column=0, sticky="nesw")
r_bracket = tk.Button(calc, text=")")
r_bracket.grid(row=1, column=1, sticky="nesw")
plus = tk.Button(calc, text="+")
plus.grid(row=5, column=3, sticky="nesw")
minus = tk.Button(calc, text="-")
minus.grid(row=4, column=3, sticky="nesw")
times = tk.Button(calc, text="*")
times.grid(row=3, column=3, sticky="nesw")
divide = tk.Button(calc, text="/")
divide.grid(row=2, column=3, sticky="nesw")
result = tk.Button(calc, text="=")
result.grid(row=5, column=2, sticky="nesw")
dot = tk.Button(calc, text=".")
dot.grid(row=5, column=1, sticky="nesw")
ans = tk.Button(calc, text="ANS")
ans.grid(row=5, column=4, sticky="nesw")

calc.mainloop()
